### ISSUE TITLE
WCF integration client - Channel in Fault State.

### ISSUE THREAD

**Issue by Davidsual** [autofac/Autofac.Wcf#4] opened 2015-10-23 11:36 UTC
Hi
I am using Autofac + Integration WCF for allowing my service to connect with other services via TCP enpoint.

Below an example of registration;

```
            builder.Register(c => new ChannelFactory<IAutomationService>(
                new NetTcpBinding(SecurityMode.None)
                {
                    CloseTimeout = TimeSpan.FromMinutes(1),
                    OpenTimeout = TimeSpan.FromMinutes(1),
                    SendTimeout = TimeSpan.FromMinutes(10),
                    ReceiveTimeout = TimeSpan.FromMinutes(10)
                },
                new EndpointAddress(ConfigurationManager.AppSettings["AutomationServiceUrl"])))
                .As<IChannelFactory<IAutomationService>>().SingleInstance();

            builder.Register(c => c.Resolve<IChannelFactory<IAutomationService>>()
                .CreateChannel(new EndpointAddress(ConfigurationManager.AppSettings["AutomationServiceUrl"])))
                .As<IAutomationService>()
                .UseWcfSafeRelease();


builder.RegisterType<CrmAutomationService>().As<ICrmAutomationService>();
```

My issue is;
When I start my service everything work correctly, my service can "talk" with other services.
But after a period of time of inactivity, when my service tries to contact other services it logs this error

System.ServiceModel.CommunicationObjectFaultedException 

The communication object, System.ServiceModel.Channels.ClientFramingDuplexSessionChannel, cannot be used for communication because it is in the Faulted state.

invoked by:

```
    public interface ICrmAutomationService
    {
        Task CreatePieceOfWorkAsync(PieceOfWork pieceOfWork);
    }

    public class CrmAutomationService: ICrmAutomationService
    {
        private readonly IAutomationService _automationService;

        public CrmAutomationService(IAutomationService automationService)
        {
            _automationService = automationService;
        }

        public async Task CreatePieceOfWorkAsync(PieceOfWork pieceOfWork)
        {
            var command = new CreatePieceOfWorkCommand {PieceOfWork = pieceOfWork.Convert()};
            await _automationService.CreatePieceOfWorkAsync(command);
        }
    }
```

The feeling is that Autofac provides me a faulted channel  [automationService], and I don't have possibility to recover from this situation unless I restart my service.

Any advice will be appreciated.

Davide

**Comment by tillig** [comment] 2015-10-23 15:26
Autofac isn't going to fault the channel unless some code you wrote is doing something to fault the channel. It's going to execute exactly what you put in the lambda - and if that creates a faulted channel, that's what it's going to hand you.

I'm not sure how you're _resolving_ dependencies, but [make sure you're using lifetime scopes and not resolving from the root container](http://autofac.readthedocs.org/en/latest/lifetime/index.html). Scopes track disposables (like your service proxy) and it holds onto them until the scope is disposed, at which point all the disposables are disposed. If you're resolving from the root container, you'll end up with all of the proxies hanging out for the lifetime of the container (a memory leak), which may at some point "max out" the number of connections you can make to the service, which, in turn, may be the cause for the faulted channels.

But there's nothing Autofac itself is doing to fault the channel. There's no magic or secret sauce. It's going to be something in your application code.

**Closed as completed by tillig** 2015-10-23 15:26 UTC
Labels: question
